apiVersion: v1
kind: Service
metadata:
  name: sentiment-wrapper-service
  namespace: retention-engine
  labels:
    app: sentiment-wrapper
spec:
  selector:
    app: sentiment-wrapper
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP